build opencv from sources instead of apt provided
apt provided opencv crash on some png files with following error:

OpenCV Error: Image step is wrong () in cvSetData, file
/build/buildd/opencv-2.4.8+dfsg1/modules/core/src/array.cpp, line 928
Traceback (most recent call last):
File "./webcam_demo.py", line 49, in <module>
rval, frame = cap.read()
cv2.error:
/build/buildd/opencv-2.4.8+dfsg1/modules/core/src/array.cpp:928:
error: (-13)  in function cvSetData

opencv from sources do not crash

Signed-off-by: Abylay Ospan <aospan@netup.ru>